name: appactiv
favicon: null
layout_spectrum: 0.4989441407378763
typography_spectrum: 0.25909734913147986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58585a'
    - '#00acd0'
    - '#dee21b'
    - '#78c35c'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.7974774108733982
purpose: []
